AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
Metrics/LineLength:
  Max: 100
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned
Lint/SuppressedException:
  Enabled: false
Metrics/AbcSize:
  Max: 18
Metrics/CyclomaticComplexity:
  Max: 8
Layout/HashAlignment:
  EnforcedColonStyle: table
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
