language: ruby

cache: bundler

rvm:
  - 2.6.5

services: mongodb

script:
  - bundle exec rake

notifications:
  email: false

deploy:
  provider: heroku
  api_key:
    secure: isnfbaqVqGL3558KBaiuZcM+5O9vZem+VhBEVP/s0K2oHburVtMNq/ws2rfi9WnD8AgyBAa6qdfp5pA2rMkt7ApP51xPPiPOmBOaayoBG8/8dErtARLf27HCaVtwjc2Xa4uzy18ObKAs5CYI33cEMnmVMgLU/cZxAqwRUUJRKyyPELrolkSYqS17cluYLEQbKL5iJmh2OOvtfaOxPUqqNjkeHeAZaBGgmhwW+mLIeSB/5LYpfahwG727fA3ONfJ2yAlBZAmYjGyD9to4i98ohN1j21hkIJXVMT9/xRf6MUxrxrQ/RFyWG3ars/3WsBdDrFPyXDCMCyxTRIEBl4UipC7h7xkxQJ86GI+uIhSAvm/t1cnclbgWwkvHPaQqUzUuSuRzuxZzf0yy9B0VhpttFXUoQLuMMMqTAlKJXINEahTy7ikrotTHu4xNZxm5+1yZlrF6KXvEYwMhWGcMvG+iVBLaosUsBmz6HVYflF4f30SJpxLkYBmYR6h1/f5sTIOxckLJWyId5BrygIGwbEx4+zovuoCQ4Aoib7fm8OsZVzKld7dSjXiw0SatkjFiaYzw6NvV3E/d3C6PUpBhKz5FCT8jAG7mS/5SUMDjsVBAuiWlxW5JaMRq5Q15OmU1FGfmVtT4X6bAqLmTbQXvwUI97AwCSJiKRVHxhyw0gQhFDYA=
  app: hitchspots
  on:
    repo: NoryDev/hitchspots
  skip_cleanup: 'true'
